# Settings for Archives Parlementaires
# You will want to copy this file and change the following settings:
# 1. log_name
# 2. default_set
# 3. coll_fld_val  (at bottom)

# log_dir:  directory for log file  (default logs, relative to harvestdor gem path)
log_dir: spec/test_logs  

# log_name: name of log file  (default: harvestdor.log)
log_name: ap.log

# purl: base url for the DOR purl server (used to get ContentMetadata, etc.)
purl: http://purl.stanford.edu

# stacks: base url for the digital stacks (no trailing slash)
stacks: https://stacks.stanford.edu

# ---------- OAI harvesting parameters -----------

# oai_client_debug:  true for OAI::Client debug mode  (default: false)

# oai_repository_url:  URL of the OAI data provider
oai_repository_url: https://dor-oaiprovider-prod.stanford.edu/oai

# default_metadata_prefix:  default metadata prefix to be used for harvesting  (default: mods)
#   can be overridden on calls to harvest_ids and harvest_records

# default_from_date:  default from date for harvest  (default: nil)
#   can be overridden on calls to harvest_ids and harvest_records

# default_until_date:  default until date for harvest  (default: nil)
#   can be overridden on calls to harvest_ids and harvest_records

# default_set:  default set for harvest  (default: nil)
#   can be overridden on calls to harvest_ids and harvest_records
default_set: is_governed_by_hy787xj5878

# Additional options to pass to Faraday http client (https://github.com/technoweenie/faraday)
http_options:
  ssl:
    verify: false
  timeout: 500
  open_timeout: 500

# ----------- SOLR index (that we're writing INTO) parameters ------------
solr:
  url: https://sul-solr-test.stanford.edu/solr/sax_profiler
#  url: http://localhost:8080/solr/sax_profiler
  read_timeout: 500
  open_timeout: 500
  
# the value of the "collection" field in the Solr document (a way to query this OAI harvest only)
# commented out for test purposes
#coll_fld_val: archives
